[package]
name = "oz-api"
license = "MIT"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4.23", features = ["serde"] }
cognitoauth = { path = "../cognitoauth" }
alloy = { workspace = true }
http = "1"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.94"
thiserror = "1.0.39"
tokio = { version = "1.17", features = ["full"] }
tracing = "0.1.37"
url = "2.3.1"
