#!/usr/bin/env python3
import os
import re
import toml
os.chdir(os.path.dirname(os.path.abspath(__file__)))
pkg = toml.load("../Cargo.toml")['package']

print(f"""\
# Do not edit, this file is automatically generated using open("../Cargo.toml", 'r').py
apiVersion: v2
version: "0.1.0"
name: {pkg['name']}
appVersion: "{pkg['version']}"
description: "{pkg['description']}"
home: {pkg['homepage']}
sources:
  - {pkg['repository']}
keywords:\
""")
for keyword in pkg['keywords']:
    print(f"  - {keyword}")
print(f"maintainers:")
for author in pkg['authors']:
    author = re.match(r'(.+)\s+<(.+)>', author)
    print(f"  - name: {author[1]}\n    email: {author[2]}")
