name: Security Audit
# See <https://github.com/marketplace/actions/rust-audit-check>

on:
  push:
    branches: [main]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC

env:
  RUST_VERSION: 1.74

jobs:
  security-audit:
    name: Dependency Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Set up Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          default: true
      - uses: rustsec/audit-check@dd51754d4e59da7395a4cd9b593f0ff2d61a9b95 # v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # False positive from cargo audit.
          # Stems from excluded optional dependency sqlx-mysql.
          # https://github.com/rustsec/rustsec/issues/1119
          ignore: "RUSTSEC-2023-0071"
