# Test these locally using [act]
# `act --container-architecture linux/amd64 -v -j build_and_push`
# [act]: https://github.com/nektos/act

name: Tests & linter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - chore/cargo-deny

env:
  RUST_VERSION: "1.88.0"
  CARGO_TERM_COLOR: always
  # Skip incremental build and debug info generation in CI
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          components: rustfmt, clippy
      - name: Install protobuf-compiler
        run: sudo apt-get install -y protobuf-compiler
      - name: Cache
        uses: actions/cache@v5
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ env.RUST_VERSION }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ env.RUST_VERSION }}-cargo-lint-
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - name: Check docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --locked --no-deps --document-private-items

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true
      - name: Install protobuf-compiler
        run: sudo apt-get install -y protobuf-compiler
      - name: Cache
        uses: actions/cache@v5
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ env.RUST_VERSION }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ env.RUST_VERSION }}-cargo-test-
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - name: Build tests
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --workspace --exclude e2e-tests --no-run
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --workspace --exclude e2e-tests

  deny:
    name: Cargo deny
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: EmbarkStudios/cargo-deny-action@3c6349835b2b7b196a839186cb8b78e02f7b5f25 # v2.1.1
        with:
          command: check ${{ matrix.checks }}
